version: '3.8'
services:
  db:
    image: mysql:8.0.33-debian
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_DATABASE=instagram-clone
      - MYSQL_ROOT_PASSWORD=root12345
    ports:
      - 3306:3306
    volumes:
      - ~/dbprojectsdata/mysql/instagram-clone:/var/lib/mysql
